version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=newwork_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80" # Map host port 80 to Nginx port 80 in the container
    depends_on:
      - db
    environment:
      - DB_NAME=newwork_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      # Superuser credentials for the first run
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=password
      - HUGGING_FACE_API_KEY=hugging_face_api_key

volumes:
  postgres_data: